services:
  - type: web
    name: igrf-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      ./predeploy.sh
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0